<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Download_dt-button-background</name>
   <tag></tag>
   <elementGuidId>bd8732a2-7c7b-4ecc-9143-79d06fe25e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dt-button-background</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bankTransferGrid_wrapper']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce4ba59f-6921-498b-9ebc-fd94f8a54aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dt-button-background</value>
      <webElementGuid>35f2c1c5-3e95-40c0-8492-cc6c4c7ed68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankTransferGrid_wrapper&quot;)/div[@class=&quot;html5buttons&quot;]/div[@class=&quot;dt-buttons btn-group flex-wrap&quot;]/div[@class=&quot;btn-group&quot;]/div[@class=&quot;dt-button-background&quot;]</value>
      <webElementGuid>9b286b8c-5b1b-495c-b93d-ed14dc8915cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bankTransferGrid_wrapper']/div/div/div/div</value>
      <webElementGuid>a75aad7c-a4ce-42d2-b99a-1c018698483e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>46edcfbf-13f0-4478-a76d-8fb3e140496e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
