<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Filter</name>
   <tag></tag>
   <elementGuidId>9aec5907-b615-4412-b715-6e06ae2b1559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bankTransferGrid_wrapper']/div/div/button/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2bc1e9b2-dd68-4384-b951-7aacb2d57d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-filter</value>
      <webElementGuid>7e63b440-0ea7-4cf1-b092-a9b1e8374f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Filter</value>
      <webElementGuid>e44c6ca7-9521-4961-a2c7-9f9ef3751d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankTransferGrid_wrapper&quot;)/div[@class=&quot;html5buttons&quot;]/div[@class=&quot;dt-buttons btn-group flex-wrap&quot;]/button[@class=&quot;btn btn-xs filterBtn btn-default&quot;]/span[1]/i[@class=&quot;fa fa-filter&quot;]</value>
      <webElementGuid>283ef4f3-c219-441a-a551-5566bdfa34a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bankTransferGrid_wrapper']/div/div/button/span/i</value>
      <webElementGuid>2be21fee-d65f-4375-9824-b8d12bab16a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manual Status Update'])[10]/following::i[1]</value>
      <webElementGuid>2cdfa414-5231-4ef0-bef1-c09ce154e922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Batch'])[10]/following::i[1]</value>
      <webElementGuid>363593bc-b153-4b0e-8327-2dc33fdcb8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::i[1]</value>
      <webElementGuid>4512cdab-0a93-4b4a-a50f-78476c6b87d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::i[1]</value>
      <webElementGuid>27d805d7-2cb5-4bd9-863d-4a9efa359124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span/i</value>
      <webElementGuid>6fcd0526-0940-4624-aeff-95ab1230dda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '  Filter' or . = '  Filter')]</value>
      <webElementGuid>52e85760-ab82-4482-842c-52cc6b3b866a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
