<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last 7 days_start</name>
   <tag></tag>
   <elementGuidId>8d1e5fd1-499a-45d1-a632-2a7dd618bb4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_start_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter_start_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cd61e7f-f20e-4b7d-be33-f228d6263083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49a55da9-974a-41ae-9494-0adb1c44633c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_start_date</value>
      <webElementGuid>df4607c3-b90d-4ef4-bd88-48b35511f90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ml-1 mr-4</value>
      <webElementGuid>3d94768e-e40c-4237-928e-e97f22fca5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>552c65e6-e7ce-44a2-bd84-abed0c0db424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>3f055c17-d438-46c6-9757-0448994a9ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_start_date&quot;)</value>
      <webElementGuid>90f59778-f5c0-46bd-a916-95eec39ec069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter_start_date']</value>
      <webElementGuid>ab416de4-b277-470c-818c-5f9f1af7fc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepicker']/input</value>
      <webElementGuid>c84ec09f-26c8-489b-8161-fe60a6784675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2209c9e6-ba9f-40f7-927e-fd66e25e140d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'filter_start_date' and @name = 'start' and @placeholder = 'Start date']</value>
      <webElementGuid>43605428-e4ec-446e-9bff-897c4abb338f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
