<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pending_checkboxValues</name>
   <tag></tag>
   <elementGuidId>2f3ad282-af9c-4fed-9414-ae6df9a919f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#failed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='failed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfc00a89-1f1d-4623-87a6-31e45191b95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>6c16c902-b8bb-4386-9610-8beb1f54d18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c6e8e55c-e9ab-49ee-8909-3b5d9c729863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>failed</value>
      <webElementGuid>6a618452-e9ec-4876-8427-d15f8bbce98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>dd19f253-15c0-46f3-9088-55d1639b90d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxValues</value>
      <webElementGuid>19ae9cee-909a-46cc-97b4-67ec47c432a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;failed&quot;)</value>
      <webElementGuid>f3c201cf-1aaf-4ce7-bfff-8fbce1bc33ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='failed']</value>
      <webElementGuid>a7d7c31f-5f47-46bc-b168-5972869c00e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filter-form']/div/div/div[3]/div/div[3]/input</value>
      <webElementGuid>abbe037b-7ed7-4983-8d62-2c26c5b0adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/input</value>
      <webElementGuid>240a87d0-e568-485d-9e0a-f96d1fa3cd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'failed' and @name = 'checkboxValues']</value>
      <webElementGuid>4082bf11-c6de-42d6-a8c4-e49d49716255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
