<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Successful_checkboxValues</name>
   <tag></tag>
   <elementGuidId>a3fd7890-253f-44cc-bdea-4cb5be797d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pending</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pending']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ab51f4e-74cc-4bf3-8c5b-42ee8429dbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f4f045a9-dc2a-490f-9f7e-f9b2e069c8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86990f99-995b-4fe3-bb79-6c4a45ca13d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pending</value>
      <webElementGuid>0581fdb1-e676-474c-b1f0-2d205a5773b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>929c89aa-c5a0-4aad-9ac6-718f330bcfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxValues</value>
      <webElementGuid>9c12f75b-d043-4604-a9a9-646955e1bfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pending&quot;)</value>
      <webElementGuid>ca0b217f-af5c-4336-bd78-ce6844cea92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pending']</value>
      <webElementGuid>9e8ac0f1-2815-429d-b8e8-45a2831f104b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filter-form']/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>f8e0f72b-2a8d-4d22-8c0a-5e6f0e043b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>43de1271-e9ac-4256-9747-b7ae2ff48d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'pending' and @name = 'checkboxValues']</value>
      <webElementGuid>290ad25b-c93f-4470-8d39-6283e058c60b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
