<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_checkboxValues</name>
   <tag></tag>
   <elementGuidId>095f9f98-039c-46dd-9743-ac3abf3a0b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfcd4e0e-5c5f-4792-8404-b93a78811ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b5112e99-0bc7-4255-98be-1d59587519c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f690fd17-4d5f-40a2-8874-8bbd0977c206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>b8bf7be8-3700-4a6e-ab44-85a7701a2bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5c907e73-a2e6-4b33-92bc-86386503865c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkboxValues</value>
      <webElementGuid>c23b8f1b-408e-4d1a-9b0f-2b36d0d43e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success&quot;)</value>
      <webElementGuid>e3c79f89-f4b2-42a5-8b7c-a03e409003be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='success']</value>
      <webElementGuid>01f1f369-6da0-471c-9152-5497d6d4fa9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='filter-form']/div/div/div[3]/div/div/input</value>
      <webElementGuid>8ad4cd95-f3fd-4654-8379-4ac8ad9a6e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>5dbcb614-3127-4974-9b9e-3c82073c9315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'success' and @name = 'checkboxValues']</value>
      <webElementGuid>1ac01b74-eace-429a-b007-0f516ab57d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
