<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Search</name>
   <tag></tag>
   <elementGuidId>e3be3bec-0d72-4334-a312-af6f51230c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bankTransferGrid_filter > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bankTransferGrid_filter']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f2a5d9f6-9379-47ed-8aab-91be7b72b17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search:</value>
      <webElementGuid>9c541da0-1913-4566-b43c-8b69f7437128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankTransferGrid_filter&quot;)/label[1]</value>
      <webElementGuid>e1e77186-f6c9-43cb-8ba6-cf2b7b9ac1b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bankTransferGrid_filter']/label</value>
      <webElementGuid>417b461b-56c2-4287-bdac-6bbfd7c54b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::label[1]</value>
      <webElementGuid>4c9f284c-3bca-443b-a2d3-a1e48dfcf2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing...'])[1]/preceding::label[1]</value>
      <webElementGuid>f1efcb9e-4b93-4783-8e43-c534fce6fc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[2]/preceding::label[1]</value>
      <webElementGuid>4228affb-9e3a-4db9-9a73-790390fc9640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/label</value>
      <webElementGuid>d5c7646a-c003-4c3a-9b17-a596f4b1c341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Search:' or . = 'Search:')]</value>
      <webElementGuid>11bd505f-5afc-4879-a071-558bd4695ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
