<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Money Out (1)</name>
   <tag></tag>
   <elementGuidId>d7d1eaef-2eb2-40b0-849f-dded8e0ed785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[2]/div/div/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7db6ad6c-3d3b-43de-9fc9-fe1b7416305c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#moneyOut</value>
      <webElementGuid>cf9818d7-6f49-4779-9703-28dbe7fced05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link</value>
      <webElementGuid>9b76f8b9-ecbc-4c03-9227-22816b5dd9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0b021afe-e8d2-41af-9d24-4e57d7733716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Money Out </value>
      <webElementGuid>1fd1a671-13d0-4532-8c74-9b6607ef0649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;wrapper   wrapper-body gray-bg dashboard-wrapper&quot;]/div[@class=&quot;full-width white-bg ibox mt-4&quot;]/div[@class=&quot;&quot;]/div[@class=&quot;wrapper  animated fadeIn  tabs-wrapper dashboard-tabs&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;full-width&quot;]/div[@class=&quot;tabs-container&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-item nav-link&quot;]</value>
      <webElementGuid>dfd6aa85-69e2-4399-bc3a-817f117b650a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[2]/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>601c59a1-39e5-4f4f-93f9-78a328f8196c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Money Out')]</value>
      <webElementGuid>d383d135-c4e6-4fb6-a493-58af4ee516cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[3]/following::a[1]</value>
      <webElementGuid>963295c2-9fdb-44a3-96dc-7ccabf1c2fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending transactions'])[1]/following::a[2]</value>
      <webElementGuid>004e3713-d26d-48ea-95d9-3cc5a114aca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Money In'])[1]/preceding::a[1]</value>
      <webElementGuid>1d146ce0-5f90-43a3-97c7-ec3f2709498a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[4]/preceding::a[2]</value>
      <webElementGuid>bead45ab-5587-46db-85f6-01b44af171db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Money Out']/parent::*</value>
      <webElementGuid>c024dbf0-9fdd-4a45-bc01-1e003249aa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#moneyOut')]</value>
      <webElementGuid>86d5c51f-5377-41b1-95e6-aadbfa91b349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[2]/a</value>
      <webElementGuid>772275c0-3c03-4aea-a897-cddfce37dc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#moneyOut' and (text() = '  Money Out ' or . = '  Money Out ')]</value>
      <webElementGuid>1756552f-1e2a-4f18-810c-33dee4c867b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
