<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overview</name>
   <tag></tag>
   <elementGuidId>c7a426bb-68b3-4d1a-9b8e-841f0ecdf310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-item.nav-link.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[4]/div[2]/div/div/div/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad7b82ba-2cca-4e21-a2a0-2021f20b3e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#overview</value>
      <webElementGuid>943d1bac-a8c8-4960-98b0-4d869237dba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link active</value>
      <webElementGuid>bd81511d-7401-4e60-9566-67f4ba1626d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2c661d72-f34c-4b55-a0b5-b8893c87f4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Overview</value>
      <webElementGuid>0af07a70-0927-4068-bb41-4df7ad6279f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;wrapper   wrapper-body gray-bg dashboard-wrapper&quot;]/div[@class=&quot;full-width white-bg ibox mt-4&quot;]/div[@class=&quot;&quot;]/div[@class=&quot;wrapper  animated fadeIn  tabs-wrapper dashboard-tabs&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;full-width&quot;]/div[@class=&quot;tabs-container&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-item nav-link active&quot;]</value>
      <webElementGuid>de419253-8f40-4e74-80ea-156ae8f0ee81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[4]/div[2]/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>5f908b67-d789-4a0d-aa02-d6a5b5eb8853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Overview')]</value>
      <webElementGuid>2b5bbb1f-7c5e-440b-85d2-c22b8c60a7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending transactions'])[1]/following::a[1]</value>
      <webElementGuid>b9f9830f-7e69-4c87-96e8-48d2b274cad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::a[1]</value>
      <webElementGuid>42c2380e-a850-42ab-a63d-b4cce39ee9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Money Out'])[1]/preceding::a[1]</value>
      <webElementGuid>248366ba-8bcb-4847-95e9-6b2b700d4598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Money In'])[1]/preceding::a[2]</value>
      <webElementGuid>8b7a3f86-96ab-4684-b4e0-ae6669619b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#overview')]</value>
      <webElementGuid>47ee6337-a2ca-4843-8ee0-9979875d6d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li/a</value>
      <webElementGuid>ec5269c9-cf4c-4a02-b5d2-a17672640559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#overview' and (text() = '  Overview' or . = '  Overview')]</value>
      <webElementGuid>f4bd703d-10e9-43ee-861e-2b0f3dbdba2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
