<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transfers</name>
   <tag></tag>
   <elementGuidId>f16019f3-dc24-4295-9bec-9b18b80f6365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transactionsLink > span.nav-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='transactionsLink']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>610dd883-d937-465f-acd9-4b3f19524aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-label</value>
      <webElementGuid>e2361c36-c74c-4392-88b6-0263425b7fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>nav.myaccounts</value>
      <webElementGuid>dcda65bc-8d86-47e1-a222-da410831ff63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfers</value>
      <webElementGuid>6cb89cdb-9fca-4dfc-9c0c-6d1589efaf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transactionsLink&quot;)/span[@class=&quot;nav-label&quot;]</value>
      <webElementGuid>148bef9d-64f4-4fdb-a7c7-d3ceef5e68a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='transactionsLink']/span</value>
      <webElementGuid>87cdf81d-16a8-47ef-91bc-908aeddd4339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[2]/following::span[2]</value>
      <webElementGuid>45278830-bb73-47d4-b0d3-37c92cbc5fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/following::span[3]</value>
      <webElementGuid>75116fed-8cb4-4252-80b1-20ac5ad7d27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting Approval'])[1]/preceding::span[2]</value>
      <webElementGuid>262b00d8-aab6-4955-afa1-7533f932efa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Links'])[1]/preceding::span[3]</value>
      <webElementGuid>73098729-f81f-408f-8a39-7a7e2c6ae265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transfers']/parent::*</value>
      <webElementGuid>6398a9a2-705d-4c6c-9203-884f75e7eaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a/span</value>
      <webElementGuid>a3c0f25a-da19-45a2-a50e-ab54b30b5509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transfers' or . = 'Transfers')]</value>
      <webElementGuid>dbf7e5d4-5b57-4ad9-8c7b-e48066c4b70e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
