<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Ref_TextBox2</name>
   <tag></tag>
   <elementGuidId>8ab87347-53d3-4715-a474-8c70481121f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextBox2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextBox2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9c6a545-c344-43a1-b1e9-b9054ed24ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>8df5077e-7930-4ef8-8b21-9288e55e17c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>132724a4-8d50-4800-8008-551f38d1b614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023May22_162417</value>
      <webElementGuid>a779e343-f19d-4491-8783-780fceb809da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>eb770ac9-3779-4579-8c48-31bcc8c84966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>99d6f949-09fe-45f6-9404-3dbfcf65b9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextBox2&quot;)</value>
      <webElementGuid>e4556887-c13b-4c2c-b247-0dd2d79c7e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextBox2']</value>
      <webElementGuid>e7b985bb-f3c5-4199-84a7-6fc225c4a7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input[2]</value>
      <webElementGuid>fd025988-46c0-4ff0-b285-af3194dcad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input[2]</value>
      <webElementGuid>e1b67512-b3f1-429d-bad8-fb0ec082828c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TextBox2' and @type = 'text' and @id = 'TextBox2']</value>
      <webElementGuid>3c3e75e7-9058-4b69-a9fa-d682cede66f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
