<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provide PRNTRN_ctl04</name>
   <tag></tag>
   <elementGuidId>88d08320-bf8a-4fcc-bb6b-860fe463f68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ctl04&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ctl04']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3fe55841-a271-4716-b586-440f1a3ec8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>92ea4ba1-1cba-4615-a7a0-391d002ab60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl04</value>
      <webElementGuid>31697a39-b431-4717-8f38-eeb8fb51c62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Validate Customer</value>
      <webElementGuid>9ee29dd6-0cf5-4133-8f47-b61b42775238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>085c125a-ddbe-498f-8d1a-0fcba9d3277f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[3]/div[@class=&quot;purchaseForm&quot;]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>9db8d4c4-51dc-4736-9b8b-1f4b116b984a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ctl04']</value>
      <webElementGuid>1496b61e-7c0d-4421-9e7c-16dc017eee03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input[2]</value>
      <webElementGuid>7ac4119c-56c0-4701-be21-58a905260995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input[2]</value>
      <webElementGuid>a81b8341-ab9f-4e36-acac-91f4079c0fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl04']</value>
      <webElementGuid>43e1a2ee-dff9-4f9e-80bd-e078bed4f278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
