<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VendorRef_TextBox3</name>
   <tag></tag>
   <elementGuidId>38188b53-9155-49e4-b2d7-4efb72e46821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextBox3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextBox3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba93b587-6ca7-4c60-b64b-414b87286293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextBox3</value>
      <webElementGuid>8223f6be-310c-410a-b1eb-b89cf2e06969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>926872fd-7e34-4faf-9490-222d4f2631f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023May22_162417</value>
      <webElementGuid>a0b51c48-6300-49d9-8273-bb175d365fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextBox3</value>
      <webElementGuid>c7796513-d659-47bb-9601-af1150978d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>42842b14-f3e8-44e8-8e23-5dbe888cd2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextBox3&quot;)</value>
      <webElementGuid>68317480-02bb-4b97-bef5-7e6519019ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextBox3']</value>
      <webElementGuid>e1940469-7151-4854-8fb1-2141a9c6f8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input</value>
      <webElementGuid>26448f28-8ee5-4e58-8c9f-f11bf6f79d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>5a447451-0b5f-4652-a3b3-eb3633a483fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TextBox3' and @type = 'text' and @id = 'TextBox3']</value>
      <webElementGuid>4c4fc725-1c04-4622-aaf8-a99ad632bfa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
