<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provide PRNTRN_CustomerRef</name>
   <tag></tag>
   <elementGuidId>bf60d116-8b4c-45dc-879d-adbfbe68a294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerRef</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerRef']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e683e16-6f9a-4bf5-a5c1-acbc1d77a060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerRef</value>
      <webElementGuid>f0e98bc6-d4f2-432e-9f49-cea0ff261393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1519e817-1861-4bbe-b3fa-8b87410aef95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerRef</value>
      <webElementGuid>a4590ee5-be8e-4216-a925-2e94783a8377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>8aed62b0-51c8-4d34-8eda-38e680ad1003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerRef&quot;)</value>
      <webElementGuid>b26fd5a1-02a9-4ff5-9e28-87193f060d08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerRef']</value>
      <webElementGuid>3533dca9-8cfc-444f-8b0f-393d0ba60e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input</value>
      <webElementGuid>d3c6fb26-1604-48eb-ab9c-83ebd82c29e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>7828e440-d55b-4dc2-a053-7dd7747346bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CustomerRef' and @type = 'text' and @id = 'CustomerRef']</value>
      <webElementGuid>d01fcd17-1f27-4ef4-bf49-1aabdad25ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
