<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Error DIGITAL TAX SOLUTIONS PRNS NOT ALLOWED</name>
   <tag></tag>
   <elementGuidId>c807c7b4-07e9-49cf-a4d3-bfbb7999bcfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errMsg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='errMsg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40b74e5b-b4ee-47aa-9b7a-5348210eeaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errMsg</value>
      <webElementGuid>24a63647-05d8-43ef-ab20-6ae9721cd840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>c90024f2-35a6-4c2f-905f-163b33a65ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error: DIGITAL TAX SOLUTIONS PRNS NOT ALLOWED!</value>
      <webElementGuid>60f6bb22-7d40-4276-95d1-627d11b3d116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errMsg&quot;)</value>
      <webElementGuid>6295e437-8b62-4a7d-88b0-590d3621584e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='errMsg']</value>
      <webElementGuid>f8867d77-5c9f-40d1-ab12-127c659f6e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/span</value>
      <webElementGuid>54731272-7504-4460-853d-b6fbffdf3d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pegasus PEGASUS Tests'])[1]/following::span[1]</value>
      <webElementGuid>dc2d1340-c7be-4238-a3fb-f7b1872325d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate Customer'])[1]/preceding::span[2]</value>
      <webElementGuid>74c34745-18b6-4fab-b5bb-07f55024fe5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide PRN/TRN'])[1]/preceding::span[3]</value>
      <webElementGuid>b1da7ce0-aea2-446e-b87c-377c31e81ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Error: DIGITAL TAX SOLUTIONS PRNS NOT ALLOWED!']/parent::*</value>
      <webElementGuid>3ac5ff8c-e6d5-4f44-a9bc-51d39e44b641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>2e385223-b4bb-400c-8c8d-f340b107cc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'errMsg' and (text() = 'Error: DIGITAL TAX SOLUTIONS PRNS NOT ALLOWED!' or . = 'Error: DIGITAL TAX SOLUTIONS PRNS NOT ALLOWED!')]</value>
      <webElementGuid>2324483a-e663-4f1c-8a3e-9e6d9cc98fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
