<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Error RECEIVED AND CREDITED</name>
   <tag></tag>
   <elementGuidId>5ec2ef2e-b82f-49c2-89c6-afd8a718a8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errMsg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='errMsg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22bac119-0598-48aa-9c48-5acb08b82197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errMsg</value>
      <webElementGuid>f396c9f7-9b56-480f-9aa5-ca1861f9dc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>1adcfcff-6383-4370-9ebb-9e71a7dff081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error: RECEIVED AND CREDITED</value>
      <webElementGuid>3cfffe50-9b88-4dd9-b35b-796e5cbae37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errMsg&quot;)</value>
      <webElementGuid>e29d4180-c6a1-42ef-94d0-62319b74f0ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='errMsg']</value>
      <webElementGuid>38cd175e-0f6d-4411-a483-d92ab17873c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/span</value>
      <webElementGuid>5528413b-e57a-4bcc-a6b6-c2499cb43453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pegasus PEGASUS Tests'])[1]/following::span[1]</value>
      <webElementGuid>f9b4744e-afbd-4f82-8a69-b8311476e19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate Customer'])[1]/preceding::span[2]</value>
      <webElementGuid>388c0ac3-1c46-4862-a148-83a39e5b9451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide PRN/TRN'])[1]/preceding::span[3]</value>
      <webElementGuid>1bf73750-54ea-46bb-b719-383f07f34fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Error: RECEIVED AND CREDITED']/parent::*</value>
      <webElementGuid>21f41480-5d17-46e4-9a4a-c3eb4784bad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>fe7db96a-feb5-42b6-a70b-67b3741b6c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'errMsg' and (text() = 'Error: RECEIVED AND CREDITED' or . = 'Error: RECEIVED AND CREDITED')]</value>
      <webElementGuid>0712ce72-4051-4fdf-9e5e-2e902d8b1045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
