<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SUCCESS</name>
   <tag></tag>
   <elementGuidId>3c09bf43-ae31-4244-8e49-020cbfa58d48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errMsg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='errMsg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0077f1a3-27d4-4fc0-9fb8-52ce17ff0f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errMsg</value>
      <webElementGuid>d37097a7-0404-40d0-9e49-134d902e010e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>f0a0e72a-5051-4b2c-bd57-406cbe6882c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUCCESS</value>
      <webElementGuid>f9fba44b-ff49-43eb-94a2-51ba57a67ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errMsg&quot;)</value>
      <webElementGuid>df353c3b-afe6-44df-b316-d5f4df02d297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='errMsg']</value>
      <webElementGuid>7887332c-1989-44a2-b62c-a8b020486b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/span</value>
      <webElementGuid>c5b70d40-4761-4de2-ba3a-38eb8376c27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pegasus PEGASUS Tests'])[1]/following::span[1]</value>
      <webElementGuid>9fe60085-d2e2-47c9-92fe-5dac368fb716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/preceding::span[2]</value>
      <webElementGuid>efac015b-ca3c-4e84-b16b-eed4d2b757ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUCCESS']/parent::*</value>
      <webElementGuid>94496c6f-8a17-40d7-a6f2-280b06f40026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>abb6bd6c-a575-4de7-96ea-4851e83f0aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'errMsg' and (text() = 'SUCCESS' or . = 'SUCCESS')]</value>
      <webElementGuid>0d4ec2c2-13f2-4851-b5b0-5c34f96042a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
