<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VendorRef_TextBox3</name>
   <tag></tag>
   <elementGuidId>cf7d48eb-3a43-4b9f-8a24-c54e893410e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextBox3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextBox3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f950d2fc-bd80-49db-85c9-554616a28d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextBox3</value>
      <webElementGuid>e06320c9-1c97-4037-a892-185f2ebbe196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6045c55f-2698-423a-a563-c53e33222caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023May19_094339</value>
      <webElementGuid>734c7e66-1cc7-4489-bf69-5f4860367cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextBox3</value>
      <webElementGuid>cfe77d30-f4b4-4b7d-a1e6-cb7e3b042ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>020fe7cc-86b7-4ea2-a22a-3a2feefcc740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextBox3&quot;)</value>
      <webElementGuid>13c7c0ae-bcf2-46ec-9f4a-9112a07559bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextBox3']</value>
      <webElementGuid>5165e197-5a1d-4951-9cb3-e34095857f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input</value>
      <webElementGuid>13f59b4c-1a00-4161-a10a-a0e3c49e8802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>35cd5a24-cdb9-42ea-a287-e48e7b018d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TextBox3' and @type = 'text' and @id = 'TextBox3']</value>
      <webElementGuid>dec610e9-c96e-445b-a4da-2febac286046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
