<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Provide PRNTRN_CustomerRef</name>
   <tag></tag>
   <elementGuidId>1be0fb3e-7d3c-4ccf-94fe-29f6e8aed0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerRef</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerRef']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb76fb78-16ac-461c-bd4a-315bfbe24b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerRef</value>
      <webElementGuid>5f900efe-0212-41cf-84c1-40134d091edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ca32f96-8c75-41ac-9f00-1486f318aa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerRef</value>
      <webElementGuid>09c541ae-09ef-48e5-92cd-68c5959f796d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>8b7137c3-7543-4e65-8288-5eec87e384c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerRef&quot;)</value>
      <webElementGuid>a9e2e2f4-c33f-47bc-b5a5-ecadce9408fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerRef']</value>
      <webElementGuid>6d25728d-cef5-486c-b605-b42420f448a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input</value>
      <webElementGuid>0c4b1f53-9632-4c12-8d14-e9b460d3581b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>0e9d4bb9-d3fd-4fb1-bd0e-714969da3df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CustomerRef' and @type = 'text' and @id = 'CustomerRef']</value>
      <webElementGuid>071bd7d8-b199-4230-991c-8bf37dd527ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
