<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Ref_TextBox2</name>
   <tag></tag>
   <elementGuidId>2c4308af-f57e-4a16-80d2-9c45674eb1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextBox2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextBox2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a5331fd-8a6c-433b-8546-b78410d5523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>deb19d07-964a-4b40-9e23-38895ae2add7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7091c6c-9a61-4276-9640-9b72e0b82f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023May19_094339</value>
      <webElementGuid>6dfff55e-930e-4a98-8838-20cd1ee77925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextBox2</value>
      <webElementGuid>cf14fb32-7c4f-4978-83f5-ffe99346be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>f554b3f6-c118-4d5a-ad52-03e04242f5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextBox2&quot;)</value>
      <webElementGuid>61c2ea95-e9d0-4e67-ba90-98b4fd13e9e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextBox2']</value>
      <webElementGuid>7d57b9e2-ca3d-40b5-9144-a2ec56ba22ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input[2]</value>
      <webElementGuid>b41acfb2-880e-479f-b787-8cbcdebe5814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input[2]</value>
      <webElementGuid>71e5b529-04c5-4fe8-9c4d-df6463313b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TextBox2' and @type = 'text' and @id = 'TextBox2']</value>
      <webElementGuid>fe3c09cc-e525-479f-b561-e0e0c30d8df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
