<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Ref_ctl08</name>
   <tag></tag>
   <elementGuidId>0f6dde5a-c89e-4aa4-8b9e-0d91c99db6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ctl08&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ctl08']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23b6db33-c336-4697-9843-6b2f4b7dcf01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>47958518-d7fd-4e99-98e1-8c0c4fe61bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl08</value>
      <webElementGuid>3eb04afa-33b0-4691-b307-9682dde02371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>d2d3a87e-9231-4038-8d03-d3173af961fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-padd</value>
      <webElementGuid>4fbd8a3b-9aa4-4ccc-afc2-1a4f34a4e4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[3]/div[@class=&quot;purchaseForm&quot;]/input[@class=&quot;btn btn-padd&quot;]</value>
      <webElementGuid>4042e73d-db09-4cc1-a776-7025f68e2770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ctl08']</value>
      <webElementGuid>7f3994b5-68d2-4d37-9129-4689935448f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input[4]</value>
      <webElementGuid>44e86c8d-4604-4e5e-9e6b-03c6768fd89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>b7e8b229-3d29-4217-ac4f-adf9b36b7145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl08']</value>
      <webElementGuid>2239d039-6f18-48ee-848a-d78aa477de31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
