<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VendorRef_ctl09</name>
   <tag></tag>
   <elementGuidId>3568009c-cf09-4c95-acbf-2d5c5c1dabda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ctl09&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ctl09']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56910e94-f27b-4a41-a463-87fdc327b977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9db0575a-604f-4403-b0a7-6f493a5f6a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl09</value>
      <webElementGuid>dfd932b4-970f-4ca5-8c2f-d457a050df65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Query Status</value>
      <webElementGuid>16229cc3-0623-4ba7-86d0-f74bf872f3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn </value>
      <webElementGuid>2da3b048-674d-4085-b0b0-a94b4ce1ab5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[3]/div[@class=&quot;purchaseForm&quot;]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>c1d2fd74-86b0-4172-b040-51e5032444c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ctl09']</value>
      <webElementGuid>9426d7b5-9319-4210-8b08-4cb91058abf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input[2]</value>
      <webElementGuid>73f4be49-4cdf-4a4c-be91-facaeea46ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input[2]</value>
      <webElementGuid>94faf7ea-cdf0-44fa-8030-051d7963665e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl09']</value>
      <webElementGuid>166632f9-3311-4169-96c1-cfe113fcb3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
