<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_TextBox1</name>
   <tag></tag>
   <elementGuidId>a562e1c3-9009-4610-933b-89421a511a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextBox1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextBox1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b593de1-4536-4809-9e49-1ed5beaa015c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TextBox1</value>
      <webElementGuid>bc94a035-4673-4fc4-b3c2-049f6800c3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>060b7468-dac7-4839-9d89-c39cd60cb79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>746325</value>
      <webElementGuid>92472178-665e-420f-8126-e3af5c7e3763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>524bfb54-0ac6-4b42-a927-1c2e64613c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextBox1</value>
      <webElementGuid>f5e4a50c-aff6-431d-8739-303b875e9570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText</value>
      <webElementGuid>086e6a22-80d9-42aa-b03c-3dc43beecb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextBox1&quot;)</value>
      <webElementGuid>4a87788a-d66a-4e7d-a6b3-5100da1934d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextBox1']</value>
      <webElementGuid>86aed74d-5caa-40cf-99ee-9cf2293ac605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/input</value>
      <webElementGuid>e78ec5c4-486d-491a-9713-1f88083859c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>ac4e1483-389b-4028-883d-d8945fbd32d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'TextBox1' and @type = 'text' and @id = 'TextBox1']</value>
      <webElementGuid>0c6f4ca4-5615-4ee6-8881-7e779b96d353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
