<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Error RECEIVED AND CREDITED</name>
   <tag></tag>
   <elementGuidId>86b8d545-59c8-4ff3-b439-d9975e078f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errMsg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='errMsg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>80c96178-49fc-401f-a001-0f2934a732aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errMsg</value>
      <webElementGuid>9b6725d4-2a71-4540-acab-89ea449eb658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>c6b351bb-a057-4ec1-8620-7ed94c9f71b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error: RECEIVED AND CREDITED</value>
      <webElementGuid>9f875f6b-27e3-42f6-be13-b2eed3ed492f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errMsg&quot;)</value>
      <webElementGuid>ef14ec34-e162-47e5-ac16-8a402a570ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='errMsg']</value>
      <webElementGuid>57478c31-b03e-4368-a973-3dc2d9511eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div/span</value>
      <webElementGuid>5f8af453-fc0b-4b64-8789-f397d0121cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pegasus PEGASUS Tests'])[1]/following::span[1]</value>
      <webElementGuid>52b37afc-de23-4fef-801e-f049e1d878e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validate Customer'])[1]/preceding::span[2]</value>
      <webElementGuid>c4287df1-5dce-4af7-91d5-6e24d72dd9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide PRN/TRN'])[1]/preceding::span[3]</value>
      <webElementGuid>82d7b0be-385f-4343-999b-cc5e663917cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Error: RECEIVED AND CREDITED']/parent::*</value>
      <webElementGuid>f2320a6e-ae1b-48fa-b50a-502fe959b413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>8798a8de-1dda-43bc-9283-71211af605bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'errMsg' and (text() = 'Error: RECEIVED AND CREDITED' or . = 'Error: RECEIVED AND CREDITED')]</value>
      <webElementGuid>7bcc24e9-de3a-47fa-99ef-ff4b055913f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
