<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TestCustomer</name>
   <tag></tag>
   <elementGuidId>90df3671-bd23-475c-b855-d1b8f5e831d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='CustName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15f4474a-3ed0-4240-86a9-86a79bdeac25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustName</value>
      <webElementGuid>1abe7430-ea1f-4ce5-8520-b7999733700f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestCustomer</value>
      <webElementGuid>9fcb6a73-7771-4c7d-9c0d-0f14561ecc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustName&quot;)</value>
      <webElementGuid>042997ed-56ea-45fe-8c7b-7aabb40dc889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='CustName']</value>
      <webElementGuid>3e0a7573-8757-4af7-aa4c-c20cf28f288d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/span[2]</value>
      <webElementGuid>68aaa358-c542-48c0-9a74-2f0965ca2b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/following::span[1]</value>
      <webElementGuid>0ce16def-a94b-4483-a455-f6ddc068b10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NSSF8991509300'])[1]/preceding::span[2]</value>
      <webElementGuid>7fd5754d-6976-45a7-9445-1118c1a0d1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::span[3]</value>
      <webElementGuid>f679cbb2-b526-4293-b5a8-96b3652950d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TestCustomer']/parent::*</value>
      <webElementGuid>b9d8ea56-a4e6-44a8-b3b4-5dac6cb8603e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>2c94963c-fac2-46dc-b77b-0291a0100e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'CustName' and (text() = 'TestCustomer' or . = 'TestCustomer')]</value>
      <webElementGuid>1cdaf800-d8a2-4bd1-ab13-534d6e50c72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
