<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_746325</name>
   <tag></tag>
   <elementGuidId>497f5946-431c-4a81-bb8e-a94e827dbde9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Balance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Balance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5294cce3-77da-4e74-8f89-1ccc4e022b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>20f3748d-fe21-4454-b836-e56ff625ecee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>746325</value>
      <webElementGuid>ce3cac3d-b2d9-41d9-96ad-f50e5fd7e741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Balance&quot;)</value>
      <webElementGuid>843af486-8668-4aa5-a741-23a2833d95c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Balance']</value>
      <webElementGuid>b9782a32-b70c-43f1-9fbf-1602d74be9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/span[3]</value>
      <webElementGuid>c737523c-ee04-43b6-a479-d1bed410e7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestCustomer'])[1]/following::span[1]</value>
      <webElementGuid>435b6032-d730-45ea-a471-9b8e681a2857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/following::span[2]</value>
      <webElementGuid>30dc016a-9c9d-4135-a079-f5684fbd9e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NSSF8991509300'])[1]/preceding::span[1]</value>
      <webElementGuid>2538658f-1fff-4637-b45f-65dd1a799dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::span[2]</value>
      <webElementGuid>3928963c-a91d-422a-a557-b0b44368f17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='746325']/parent::*</value>
      <webElementGuid>cc40232e-aac5-4eb5-b7cc-d8ce4e3613fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>11b750c7-ab50-4093-8ea8-3d61d80ab20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Balance' and (text() = '746325' or . = '746325')]</value>
      <webElementGuid>c2dcee1c-7a99-4145-9c75-dba04fdd4ba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
