<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_40000</name>
   <tag></tag>
   <elementGuidId>a6d96fa3-2a2f-4147-8ab8-12aae3c91099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Balance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Balance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea903bf2-9e49-41a3-93a7-3eba8e107717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>4e007e19-5d78-46f9-9069-1e5124844da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>40000</value>
      <webElementGuid>b4e1f41f-a9d0-48ae-9162-a4e895ae2ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Balance&quot;)</value>
      <webElementGuid>c0bdd9ed-8a6c-46a9-90e9-173aebf4b975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Balance']</value>
      <webElementGuid>5fdb0c16-97b6-46ac-a079-2ac98caa471a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/span[3]</value>
      <webElementGuid>bd0ba349-1fba-45ad-9107-ccb5db94410b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAMBAK ENTERPRISES LIMITED'])[1]/following::span[1]</value>
      <webElementGuid>22dec3f8-f7b0-4aa7-a7a6-21c025ec9f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/following::span[2]</value>
      <webElementGuid>33940fba-393a-4ea3-9f06-0bc6e515befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::span[2]</value>
      <webElementGuid>a1568612-3b44-4e73-abf9-ef15f0883407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Ref'])[1]/preceding::span[3]</value>
      <webElementGuid>26127d0a-6475-4ccc-a977-358df6312cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='40000']/parent::*</value>
      <webElementGuid>b43f02a7-63ea-4d76-95b1-15ad1efba31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>bc3d6d6d-55d3-4156-a01c-a7ac2a8b0e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Balance' and (text() = '40000' or . = '40000')]</value>
      <webElementGuid>7a7846cf-8795-475c-b47a-ab246b2332eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
