<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DAMBAK ENTERPRISES LIMITED</name>
   <tag></tag>
   <elementGuidId>b19fcfad-01e8-4299-bdc7-9efea5377296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='CustName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed7f6457-2041-44b0-a599-b712146746af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustName</value>
      <webElementGuid>de10babc-2d66-4019-9e7d-ee8eaba817fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAMBAK ENTERPRISES LIMITED</value>
      <webElementGuid>d92b745d-0946-4954-9077-7b7b2f9d548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustName&quot;)</value>
      <webElementGuid>d523c934-18c8-47c3-9290-b915758b957d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='CustName']</value>
      <webElementGuid>be42bf38-e974-4876-8a79-abaa35e38b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/span[2]</value>
      <webElementGuid>4a55a683-eb7b-4a91-9718-9fa35142dc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/following::span[1]</value>
      <webElementGuid>a4f0fcb8-2be7-4f77-ae50-5173e3c4908a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::span[3]</value>
      <webElementGuid>3e215000-c5d2-4214-93a2-2ca7c9e3298d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Ref'])[1]/preceding::span[4]</value>
      <webElementGuid>fe36ca57-3ea7-40bd-8ab1-c49f6d649900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAMBAK ENTERPRISES LIMITED']/parent::*</value>
      <webElementGuid>7cbeb624-7e11-48da-9fb2-2d89d5ad8faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>9c946507-76fd-4e89-821e-1ab6d988567a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'CustName' and (text() = 'DAMBAK ENTERPRISES LIMITED' or . = 'DAMBAK ENTERPRISES LIMITED')]</value>
      <webElementGuid>c5726e65-6803-4ffb-b710-3684addffe79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
